version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kea
      MYSQL_DATABASE: kea
      MYSQL_USER: kea
      MYSQL_PASSWORD: kea
    ports:
      - "127.0.0.1:3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "127.0.0.1:8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/kea?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: kea
      SPRING_DATASOURCE_PASSWORD: kea
    depends_on:
      mysql:
        condition: service_healthy
    command: >
      sh -c "
        while ! nc -z mysql 3306; do
          echo 'Waiting for MySQL...'
          sleep 1
        done
        echo 'MySQL is ready!'
        java -jar app.jar
      "

volumes:
  mysql_data:
